// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArzaIDl88KWW2lN2uZptu66OaGk-TO2C0',
    appId: '1:403069365842:web:7a1c49a1f28764c758798b',
    messagingSenderId: '403069365842',
    projectId: 'selfattendance-f846e',
    authDomain: 'selfattendance-f846e.firebaseapp.com',
    storageBucket: 'selfattendance-f846e.firebasestorage.app',
    measurementId: 'G-JDE49CQ302',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlhmvDMn4wpGwWhL5Fi48NxHFiVQ79kKA',
    appId: '1:403069365842:android:1a640f0f319472de58798b',
    messagingSenderId: '403069365842',
    projectId: 'selfattendance-f846e',
    storageBucket: 'selfattendance-f846e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXtSqhHukNexjMSZTmcV2x-Cit6PSxR2Y',
    appId: '1:403069365842:ios:3149bdcbafb8b7c358798b',
    messagingSenderId: '403069365842',
    projectId: 'selfattendance-f846e',
    storageBucket: 'selfattendance-f846e.firebasestorage.app',
    iosBundleId: 'com.example.selfattendenceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXtSqhHukNexjMSZTmcV2x-Cit6PSxR2Y',
    appId: '1:403069365842:ios:3149bdcbafb8b7c358798b',
    messagingSenderId: '403069365842',
    projectId: 'selfattendance-f846e',
    storageBucket: 'selfattendance-f846e.firebasestorage.app',
    iosBundleId: 'com.example.selfattendenceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArzaIDl88KWW2lN2uZptu66OaGk-TO2C0',
    appId: '1:403069365842:web:a3c55f461ef4d38f58798b',
    messagingSenderId: '403069365842',
    projectId: 'selfattendance-f846e',
    authDomain: 'selfattendance-f846e.firebaseapp.com',
    storageBucket: 'selfattendance-f846e.firebasestorage.app',
    measurementId: 'G-METPDW6DYX',
  );

}